### PR TITLE
add assume_service to aws-iam-role

### PR DESCRIPTION
**Pull request by BumbleFeng**
Signed-off-by: Feng Huang <fehuang@redhat.com>

### CODE REVIEW

**Comment by maorfr** [comment]
What about:
```
assume_role:
- kind: AWS
  arn: <role_arn>
- kind: Service
  arn: <service_arn>
```

**Comment by BumbleFeng** [comment]
> What about:
> 
> ```
> assume_role:
> - kind: AWS
>   arn: <role_arn>
> - kind: Service
>   arn: <service_arn>
> ```

how about:
```
assume_role:
  AWS:
  - <role_arn1>
  - <role_arn2>
  Service:
  - <service_arn1>
  - <service_arn2>
```

**Comment by BumbleFeng** [comment]
> What about:
> 
> ```
> assume_role:
> - kind: AWS
>   arn: <role_arn>
> - kind: Service
>   arn: <service_arn>
> ```

how about:
```
assume_role:
  AWS:
  - <role_arn1>
  - <role_arn2>
  Service:
  - <service_arn1>
  - <service_arn2>
```

**Comment by maorfr** [comment]
LGTM!

**Review by maorfr — APPROVED** [review]

**Pull request merged**
