### PR TITLE
APPSRE-10782 add optional TGW conection cidrBlocks field

### PR DESCRIPTION
**Pull request by patjlm**
https://issues.redhat.com/browse/APPSRE-10782

This will allow to route multiple cidr blocks towards a TGW

### CODE REVIEW

**Comment by rporres** [comment]
What's the plan here? move all cidrBlock to cidrBlocks and remove cidrBlock in the near future?

**Comment by patjlm** [comment]
> What's the plan here? move all cidrBlock to cidrBlocks and remove cidrBlock in the near future?

that would be best but nor fully required. This needs to be synced with all instances where we use TGW attachements (incl fedramp i suppose).

**Comment by rporres** [comment]
Reading the code I don't think it is feasible to remove `cidrBlock` as I understand that you need to define the `moved` block.

I would then add documentation in the schema to state the usage of `cidrBlock` is deprecated and that `cidrBlocks` should be used instead for new attachments.

**Comment by patjlm** [comment]
Once the resource has been renamed, the `moved` block is not needed and can be removed. At that point we can remove safely `cidrBlock` and move its value within `cidrBlocks`

**Comment by rporres** [comment]
Great, then at some point we can remove cidrBlock from the schema and just use cidrBlocks

As for the deprecation message, I'd just add a note in the `description` field.

**Review by rporres — APPROVED** [review]

**Pull request merged**
