### PR TITLE
APPSRE-3556 deprecate saas-file-1

### PR DESCRIPTION
**Pull request by fishi0x01**
All saas files are moved to tekton. We can deprecate `saas-file-1` now.

### CODE REVIEW

**Comment by janboll** [comment]
:question: Still found a couple of references in app-interface

**Review by rporres — APPROVED** [review]
To be fair, you're not deprecating, you're actually removing the support for saas-file-1.yml files :-D

LGTM otherwise

**Comment by fishi0x01** [comment]
@janboll good catch! Thank you! :bow: 
Removed the occurrences in app-interface.

**Comment by maorfr** [comment]
just like we add schemas before logic, we should remove logic before schemas.

going to revert this one to promote the next PR, but this by no means mean this PR is not good :)

**Pull request merged**
