### PR TITLE
indicate an rds instance is used as a grafana datasource

### PR DESCRIPTION
**Pull request by maorfr**
this can be used for multiple purposes, such as audit, self-service, automation, and more.

### CODE REVIEW

**Comment by geoberle** [comment]
so e.g. add such a flagged RDS instance to grafana automatically? or at least report on it if it is present there without being flagged?

**Comment by maorfr** [comment]
absolutely. and perhaps more around compliance, and anything else we may need.

**Comment by maorfr** [comment]
related to https://issues.redhat.com/browse/APPSRE-6791

**Review by pontg — APPROVED** [review]

**Review by geoberle — APPROVED** [review]
valuable for compliance!

**Pull request merged**
